apiVersion: v1
kind: Pod
metadata:
  name: userns-disabled
  namespace: default
spec:
  hostUsers: true
  containers:
  - name: app
    image: nginx:1.25
    securityContext:
      allowPrivilegeEscalation: false
